/* Generated By:JJTree: Do not edit this line. XMLNamespaces.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.symbol;

import java.util.ArrayList;
import java.util.List;
import org.teiid.designer.query.sql.symbol.IXMLNamespaces;
import org.teiid.designer.runtime.version.spi.ITeiidServerVersion;
import org.teiid.query.parser.LanguageVisitor;
import org.teiid.query.sql.lang.NamespaceItem;
import org.teiid.query.sql.lang.SimpleNode;

/**
 *
 */
public class XMLNamespaces extends SimpleNode implements IXMLNamespaces<LanguageVisitor> {

    private List<NamespaceItem> namespaceItems;

    /**
     * @param p
     * @param id
     */
    public XMLNamespaces(ITeiidServerVersion p, int id) {
        super(p, id);
    }

    /**
     * @return the namespaceItems
     */
    public List<NamespaceItem> getNamespaceItems() {
        return this.namespaceItems;
    }

    /**
     * @param namespaceItems the namespaceItems to set
     */
    public void setNamespaces(List<NamespaceItem> namespaceItems) {
        this.namespaceItems = namespaceItems;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.namespaceItems == null) ? 0 : this.namespaceItems.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        XMLNamespaces other = (XMLNamespaces)obj;
        if (this.namespaceItems == null) {
            if (other.namespaceItems != null) return false;
        } else if (!this.namespaceItems.equals(other.namespaceItems)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(LanguageVisitor visitor) {
        visitor.visit(this);
    }

    @Override
    public XMLNamespaces clone() {
        XMLNamespaces clone = new XMLNamespaces(getTeiidVersion(), this.id);

        if(getNamespaceItems() != null) {
            List<NamespaceItem> cloneList = new ArrayList<NamespaceItem>();
            for (NamespaceItem item : getNamespaceItems()) {
                cloneList.add(item.clone());
            }
            clone.setNamespaces(cloneList);
        }

        return clone;
    }

}
/* JavaCC - OriginalChecksum=736a2961c19def96febeb5ccbed0cdcf (do not edit this line) */
