<?xml version="1.0" encoding="ASCII"?>
<!--  Copyright (c) 2000-2005 MetaMatrix, Inc.  All rights reserved. -->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dependency"
    nsURI="http://www.metamatrix.com/metamodels/Dependency" nsPrefix="dependency">
  <eClassifiers xsi:type="ecore:EClass" name="DependencyInfo"/>
</ecore:EPackage>
