/* Generated By:JJTree: Do not edit this line. Alter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;

public class Alter extends Command {

    public static enum AlterType {
        VIEW,
        TRIGGER,
        PROCEDURE;
    }

    public static enum TriggerEvent {
        INSERT,
        UPDATE,
        DELETE
    }

    private AlterType alterType;

    private GroupSymbol target;

    private Command definition;

    private TriggerEvent event;

    private boolean create;

    private Boolean enabled;

    public Alter(int id) {
        super(id);
    }

    public Alter(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the alterType
     */
    public AlterType getAlterType() {
        return this.alterType;
    }

    /**
     * @param alterType the type of Alter object
     */
    public void setAlterType(AlterType alterType) {
        this.alterType = alterType;
    }

    /**
     * @return the target
     */
    public GroupSymbol getTarget() {
        return this.target;
    }

    /**
     * @param target the target to set
     */
    public void setTarget(GroupSymbol target) {
        this.target = target;
    }

    /**
     * @return the definition
     */
    public Command getDefinition() {
        return definition;
    }

    /**
     * @param definition the definition to set
     */
    public void setDefinition(Command definition) {
        this.definition = definition;
    }

    /**
     * @return the event
     */
    public TriggerEvent getEvent() {
        return event;
    }

    /**
     * @param event the event to set
     */
    public void setEvent(TriggerEvent event) {
        this.event = event;
    }

    /**
     * @return the create
     */
    public boolean isCreate() {
        return create;
    }

    /**
     * @param create the create to set
     */
    public void setCreate(boolean create) {
        this.create = create;
    }

    /**
     * @return the enabled
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * @param enabled the enabled to set
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.alterType == null) ? 0 : this.alterType.hashCode());
        result = prime * result + (this.create ? 1231 : 1237);
        result = prime * result + ((this.definition == null) ? 0 : this.definition.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        result = prime * result + ((this.event == null) ? 0 : this.event.hashCode());
        result = prime * result + ((this.target == null) ? 0 : this.target.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        Alter other = (Alter)obj;
        if (this.alterType != other.alterType) return false;
        if (this.create != other.create) return false;
        if (this.definition == null) {
            if (other.definition != null) return false;
        } else if (!this.definition.equals(other.definition)) return false;
        if (this.enabled == null) {
            if (other.enabled != null) return false;
        } else if (!this.enabled.equals(other.enabled)) return false;
        if (this.event != other.event) return false;
        if (this.target == null) {
            if (other.target != null) return false;
        } else if (!this.target.equals(other.target)) return false;
        return true;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=4c2a7e700d4af2b1569d4947a1d82223 (do not edit this line) */
