/* Generated By:JJTree: Do not edit this line. BetweenCriteria.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;

public class BetweenCriteria extends Criteria {

    private Expression expression;

    private Expression lowerExpression;

    private Expression upperExpression;
    
    /** Negation flag. Indicates whether the criteria expression contains a NOT. */
    private boolean negated = false;

    public BetweenCriteria(int id) {
        super(id);
    }

    public BetweenCriteria(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the expression
     */
    public Expression getExpression() {
        return this.expression;
    }

    /**
     * @param expression the expression to set
     */
    public void setExpression(Expression expression) {
        this.expression = expression;
    }

    /**
     * @return the lowerExpression
     */
    public Expression getLowerExpression() {
        return this.lowerExpression;
    }

    /**
     * @param lowerExpression the lowerExpression to set
     */
    public void setLowerExpression(Expression lowerExpression) {
        this.lowerExpression = lowerExpression;
    }

    /**
     * @return the upperExpression
     */
    public Expression getUpperExpression() {
        return this.upperExpression;
    }

    /**
     * @param upperExpression the upperExpression to set
     */
    public void setUpperExpression(Expression upperExpression) {
        this.upperExpression = upperExpression;
    }

    /**
     * @return the negated
     */
    public boolean isNegated() {
        return this.negated;
    }

    /**
     * @param negated the negated to set
     */
    public void setNegated(boolean negated) {
        this.negated = negated;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=c3fc97791e1610f2c6a0633d0ef3c39c (do not edit this line) */
