/* Generated By:JJTree: Do not edit this line. CommandStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;

public class CommandStatement extends Statement {

    // the command this statement represents
    private Command command;

    private boolean returnable = true;

    public CommandStatement(int id) {
        super(id);
    }

    public CommandStatement(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * Get the command on this statement.
     * @return The <code>Command</code> on this statement
     */
    public Command getCommand() {
        return command; 
    }

    public void setCommand(Command command){
        this.command = command;
    }

    public boolean isReturnable() {
        return returnable;
    }
    
    public void setReturnable(boolean returnable) {
        this.returnable = returnable;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=62f9df6ce048861851414036eed990e3 (do not edit this line) */
