/* Generated By:JJTree: Do not edit this line. CreateUpdateProcedureCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.designer.annotation.Removed;
import org.teiid.runtime.client.lang.parser.TeiidParser;

@Removed("8.0.0")
public class CreateUpdateProcedureCommand extends Command {

    // top level block for the procedure
    private Block block;

    //whether it is update procedure or virtual stored procedure, default to update procedure
    private boolean isUpdateProcedure = true;

    public CreateUpdateProcedureCommand(int id) {
        super(id);
    }

    public CreateUpdateProcedureCommand(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * Get the block on this command.
     * @return The <code>Block</code> on this command
     */
    public Block getBlock() {
        return block;
    }

    /**
     * Set the block on this command.
     * @param block The <code>Block</code> on this command
     */
    public void setBlock(Block block) {
        this.block = block;
    }

    /**
     * @return the isUpdateProcedure
     */
    public boolean isUpdateProcedure() {
        return this.isUpdateProcedure;
    }

    /**
     * @param isUpdateProcedure the isUpdateProcedure to set
     */
    public void setUpdateProcedure(boolean isUpdateProcedure) {
        this.isUpdateProcedure = isUpdateProcedure;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid7ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=f346ab2e5ff020b1b349d6d7fdcc5974 (do not edit this line) */
