/* Generated By:JJTree: Do not edit this line. CreateProcedureCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.designer.annotation.Since;
import org.teiid.runtime.client.lang.parser.TeiidParser;

@Since("8.0.0")
public class CreateProcedureCommand extends Command {

    // top level block for the procedure
    private Block block;

    public CreateProcedureCommand(int id) {
        super(id);
    }

    public CreateProcedureCommand(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the block
     */
    public Block getBlock() {
        return block;
    }

    /**
     * @param block the block to set
     */
    public void setBlock(Block block) {
        this.block = block;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=14790ffe7d56203cb640dd53367c0c33 (do not edit this line) */
