/* Generated By:JJTree: Do not edit this line. Drop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;

public class Drop extends Command {

    /** Identifies the table to be dropped. */
    private GroupSymbol table;

    public Drop(int id) {
        super(id);
    }

    public Drop(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the table
     */
    public GroupSymbol getTable() {
        return table;
    }

    /**
     * @param table the table to set
     */
    public void setTable(GroupSymbol table) {
        this.table = table;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=cf112d019f8dc39785f359562092f510 (do not edit this line) */
