/* Generated By:JJTree: Do not edit this line. ProjectedColumn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.TeiidNodeFactory.CommonNodes;
import org.teiid.runtime.client.lang.parser.TeiidParser;

public class ProjectedColumn extends SimpleNode {
    
    private String name;

    private String type;

    private ElementSymbol symbol;

    public ProjectedColumn(int id) {
        super(id);
    }

    public ProjectedColumn(TeiidParser p, int id) {
        super(p, id);
    }

    public ElementSymbol getSymbol() {
        return symbol;
    }

    /**
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
        this.symbol = parser.createCommonNode(CommonNodes.ELEMENT_SYMBOL);
        this.symbol.setName(name);
    }

    /**
     * @return the type
     */
    public String getType() {
        return this.type;
    }

    /**
     * @param type the type to set
     */
    public void setType(String type) {
        this.type = type;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=991e5fb319eb5a871b3cd33dacf6a7ed (do not edit this line) */
