/* Generated By:JJTree: Do not edit this line. ScalarSubquery.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;

public class ScalarSubquery extends SimpleNode implements Expression {

    private QueryCommand command;

    private Class<?> type;

    public ScalarSubquery(int id) {
        super(id);
    }

    public ScalarSubquery(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the command
     */
    public QueryCommand getCommand() {
        return command;
    }

    /**
     * @param command the command to set
     */
    public void setCommand(QueryCommand command) {
        this.command = command;
    }

    @Override
    public Class<?> getType() {
        // TODO
//        if (this.type == null){
//            Expression symbol = this.command.getProjectedSymbols().iterator().next();
//            this.type = symbol.getType();
//        }
        //may still be null if this.command wasn't resolved
        return this.type;
    }

    /**
     * Set type of ScalarSubquery
     * @param type New type
     */
    public void setType(Class<?> type) {
        this.type = type;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }

    
}
/* JavaCC - OriginalChecksum=bfe243691ae4c256b98aff43709faeed (do not edit this line) */
