/* Generated By:JJTree: Do not edit this line. SetCriteria.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import java.util.List;
import org.teiid.runtime.client.lang.parser.TeiidParser;

public class SetCriteria extends AbstractSetCriteria {

    /** The set of value expressions */
    private List<Expression> values;

    public SetCriteria(int id) {
        super(id);
    }

    public SetCriteria(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the values
     */
    public List<Expression> getValues() {
        return this.values;
    }

    /**
     * @param values the values to set
     */
    public void setValues(List<Expression> values) {
        this.values = values;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=9f7eb5b2819c59fc94d4b273872b85f1 (do not edit this line) */
