/* Generated By:JJTree: Do not edit this line. TextColumn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;

public class TextColumn extends ProjectedColumn {

    private Integer width;

    private boolean noTrim;

    private String selector;

    private Integer position;

    public TextColumn(int id) {
        super(id);
    }

    public TextColumn(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the width
     */
    public Integer getWidth() {
        return this.width;
    }

    /**
     * @param width the width to set
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * @return the noTrim
     */
    public boolean isNoTrim() {
        return this.noTrim;
    }

    /**
     * @param noTrim the noTrim to set
     */
    public void setNoTrim(boolean noTrim) {
        this.noTrim = noTrim;
    }

    /**
     * @return the selector
     */
    public String getSelector() {
        return this.selector;
    }

    /**
     * @param selector the selector to set
     */
    public void setSelector(String selector) {
        this.selector = selector;
    }

    /**
     * @return the position
     */
    public Integer getPosition() {
        return this.position;
    }

    /**
     * @param position the position to set
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=b1ade91310a19786192f5e8514ff33a8 (do not edit this line) */
