/* Generated By:JJTree: Do not edit this line. UnaryFromClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;

public class UnaryFromClause extends FromClause {

    private GroupSymbol groupSymbol;
    
    private Command expandedCommand;
    
    public UnaryFromClause(int id) {
        super(id);
    }

    public UnaryFromClause(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the groupSymbol
     */
    public GroupSymbol getGroupSymbol() {
        return groupSymbol;
    }

    /**
     * @param groupSymbol the groupSymbol to set
     */
    public void setGroupSymbol(GroupSymbol groupSymbol) {
        this.groupSymbol = groupSymbol;
    }

    /**
     * @return the expandedCommand
     */
    public Command getExpandedCommand() {
        return expandedCommand;
    }

    /**
     * @param expandedCommand the expandedCommand to set
     */
    public void setExpandedCommand(Command expandedCommand) {
        this.expandedCommand = expandedCommand;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=363ebf15eecd5ebdaa922627c2a7905d (do not edit this line) */
