/* Generated By:JJTree: Do not edit this line. XMLAttributes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import java.util.List;
import org.teiid.runtime.client.lang.parser.TeiidParser;

public class XMLAttributes extends SimpleNode {

    private List<DerivedColumn> args;

    public XMLAttributes(int id) {
        super(id);
    }

    public XMLAttributes(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the args
     */
    public List<DerivedColumn> getArgs() {
        return this.args;
    }

    /**
     * @param args the args to set
     */
    public void setArgs(List<DerivedColumn> args) {
        this.args = args;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=b3038eb7357f2bdba91bc701ecebddd9 (do not edit this line) */
