/* Generated By:JJTree: Do not edit this line. XMLSerialize.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast;

import org.teiid.runtime.client.lang.parser.TeiidParser;
import org.teiid.runtime.client.types.DataTypeManagerService;

public class XMLSerialize extends SimpleNode implements Expression {

    private Boolean document;

    private Boolean declaration;

    private Expression expression;

    private String typeString;

    private Class<?> type;

    private String version;

    private String encoding;

    public XMLSerialize(int id) {
        super(id);
    }

    public XMLSerialize(TeiidParser p, int id) {
        super(p, id);
    }

    /**
     * @return the document
     */
    public Boolean getDocument() {
        return this.document;
    }

    /**
     * @param document the document to set
     */
    public void setDocument(Boolean document) {
        this.document = document;
    }

    /**
     * @return the declaration
     */
    public Boolean getDeclaration() {
        return this.declaration;
    }

    /**
     * @param declaration the declaration to set
     */
    public void setDeclaration(Boolean declaration) {
        this.declaration = declaration;
    }

    /**
     * @return the expression
     */
    public Expression getExpression() {
        return this.expression;
    }

    /**
     * @param expression the expression to set
     */
    public void setExpression(Expression expression) {
        this.expression = expression;
    }

    /**
     * @return the version
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * @param version the version to set
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * @return the encoding
     */
    public String getEncoding() {
        return this.encoding;
    }

    /**
     * @param encoding the encoding to set
     */
    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }

    @Override
    public Class<?> getType() {
        if (type == null) {
            if (typeString == null) {
                type = DataTypeManagerService.DefaultDataTypes.CLOB.getClass();
            } else {
                parser.getDataTypeService().getDataTypeClass(typeString);
            }
        }
        return type;
    }

    public void setTypeString(String typeString) {
        this.typeString = typeString;
    }
    
    public String getTypeString() {
        return typeString;
    }

    /** Accept the visitor. **/
    public void jjtAccept(Teiid8ParserVisitor visitor, Object data) {
        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=2db0f3a9bb9c785d22f2f82535419c33 (do not edit this line) */
