/* Generated By:JavaCC: Do not edit this line. SQLParserTreeConstants.java Version 5.0 */
package org.teiid.query.sql.lang;

import org.teiid.query.parser.*;

public interface SQLParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
/* JavaCC - OriginalChecksum=7f1f23b16c3c6d960f54b92dd4ffd475 (do not edit this line) */
