<?xml version="1.0" encoding="ASCII"?>
<!--  Copyright (c) 2000-2005 MetaMatrix, Inc.  All rights reserved. -->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aspinventory"
    nsURI="http://www.metamatrix.com/metamodels/demo/AspInventory" nsPrefix="aspinventory">
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationSystem">
    <eReferences name="codeBase" eType="#//CodeBase" lowerBound="1" eOpposite="#//CodeBase/applicationSystems"/>
    <eReferences name="customers" eType="#//Customer" upperBound="-1" eOpposite="#//Customer/applicationSystems"/>
    <eReferences name="functions" eType="#//Function" lowerBound="1" upperBound="-1"
        containment="true" eOpposite="#//Function/applicationSystems"/>
    <eReferences name="servers" eType="#//Server" upperBound="-1" eOpposite="#//Server/applicationSystems"/>
    <eAttributes name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="revenue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eAttributes name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eAttributes name="productLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="businessUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eReferences name="storage" eType="#//Storage" upperBound="-1" containment="true"
        eOpposite="#//Storage/servers"/>
    <eReferences name="applicationSystems" eType="#//ApplicationSystem" upperBound="-1"
        eOpposite="#//ApplicationSystem/servers"/>
    <eAttributes name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="vendor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eAttributes name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eAttributes name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eReferences name="relatedFunctions" eType="#//Function" upperBound="-1"/>
    <eReferences name="dataEntities" eType="ecore:EClass ../Relational.ecore#//Table"
        upperBound="-1"/>
    <eReferences name="applicationSystems" eType="#//ApplicationSystem" transient="true"
        lowerBound="1" eOpposite="#//ApplicationSystem/functions"/>
    <eAttributes name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eReferences name="applicationSystems" eType="#//ApplicationSystem" upperBound="-1"
        eOpposite="#//ApplicationSystem/customers"/>
    <eAttributes name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="revenue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eAttributes name="segment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage">
    <eReferences name="servers" eType="#//Server" transient="true" lowerBound="1"
        eOpposite="#//Server/storage"/>
    <eAttributes name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="vendor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="modelNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="diskSizeInKb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eAttributes name="diskSizeInMb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eAttributes name="diskSizeInGb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eAttributes name="type" eType="#//StorageType" defaultValueLiteral="LOCAL_STORAGE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBase">
    <eReferences name="applicationSystems" eType="#//ApplicationSystem" upperBound="-1"
        eOpposite="#//ApplicationSystem/codeBase"/>
    <eAttributes name="technology" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StorageType">
    <eLiterals name="STORAGE_AREA_NETWORK"/>
    <eLiterals name="NETWORK_AREA_STORAGE" value="1"/>
    <eLiterals name="LOCAL_STORAGE" value="2"/>
  </eClassifiers>
</ecore:EPackage>
