<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="http"
    nsURI="http://schemas.xmlsoap.org/wsdl/http/" nsPrefix="http">
  <eClassifiers xsi:type="ecore:EClass" name="HttpAddress">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass wsdl.ecore#//Port"
        transient="true" eOpposite="wsdl.ecore#//Port/httpAddress"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
        eType="ecore:EClass wsdl.ecore#//Binding" transient="true" eOpposite="wsdl.ecore#//Binding/httpBinding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingOperation" lowerBound="1"
        eType="ecore:EClass wsdl.ecore#//BindingOperation" transient="true" eOpposite="wsdl.ecore#//BindingOperation/httpOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
