<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mime"
    nsURI="http://schemas.xmlsoap.org/wsdl/mime/" nsPrefix="mime">
  <eClassifiers xsi:type="ecore:EClass" name="MimeContent" eSuperTypes="#//MimeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagePart" eType="ecore:EClass wsdl.ecore#//MessagePart"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xml" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MimeMultipartRelated" eSuperTypes="#//MimeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mimeParts" upperBound="-1"
        eType="#//MimePart" containment="true" eOpposite="#//MimePart/mimeMultipartRelated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MimePart" eSuperTypes="#//MimeElementOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mimeMultipartRelated" lowerBound="1"
        eType="#//MimeMultipartRelated" transient="true" eOpposite="#//MimeMultipartRelated/mimeParts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MimeElementOwner" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mimeElements" upperBound="-1"
        eType="#//MimeElement" containment="true" eOpposite="#//MimeElement/mimeElementOwner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MimeElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mimeElementOwner" lowerBound="1"
        eType="#//MimeElementOwner" transient="true" eOpposite="#//MimeElementOwner/mimeElements"/>
  </eClassifiers>
</ecore:EPackage>
