<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soap"
    nsURI="http://schemas.xmlsoap.org/wsdl/soap/" nsPrefix="soap">
  <eClassifiers xsi:type="ecore:EClass" name="SoapAddress">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass wsdl.ecore#//Port"
        transient="true" eOpposite="wsdl.ecore#//Port/soapAddress"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoapHeaderFault" eSuperTypes="#//SoapFault">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagePart" upperBound="-1"
        eType="ecore:EClass wsdl.ecore#//MessagePart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soapHeader" lowerBound="1"
        eType="#//SoapHeader" transient="true" eOpposite="#//SoapHeader/headerFault"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parts" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SoapStyleType">
    <eLiterals name="RPC"/>
    <eLiterals name="DOCUMENT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SoapUseType">
    <eLiterals name="LITERAL"/>
    <eLiterals name="ENCODED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoapFault">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingFault" eType="ecore:EClass wsdl.ecore#//BindingFault"
        transient="true" eOpposite="wsdl.ecore#//BindingFault/soapFault"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="use" eType="#//SoapUseType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodingStyles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoapHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingParam" lowerBound="1"
        eType="ecore:EClass wsdl.ecore#//BindingParam" transient="true" eOpposite="wsdl.ecore#//BindingParam/soapHeader"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagePart" upperBound="-1"
        eType="ecore:EClass wsdl.ecore#//MessagePart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headerFault" eType="#//SoapHeaderFault"
        containment="true" eOpposite="#//SoapHeaderFault/soapHeader"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="use" eType="#//SoapUseType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodingStyles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parts" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoapBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingParam" lowerBound="1"
        eType="ecore:EClass wsdl.ecore#//BindingParam" transient="true" eOpposite="wsdl.ecore#//BindingParam/soapBody"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="use" eType="#//SoapUseType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodingStyles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parts" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoapOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingOperation" lowerBound="1"
        eType="ecore:EClass wsdl.ecore#//BindingOperation" transient="true" eOpposite="wsdl.ecore#//BindingOperation/soapOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="#//SoapStyleType"
        defaultValueLiteral="DOCUMENT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoapBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
        eType="ecore:EClass wsdl.ecore#//Binding" transient="true" eOpposite="wsdl.ecore#//Binding/soapBinding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="#//SoapStyleType"
        defaultValueLiteral="DOCUMENT"/>
  </eClassifiers>
</ecore:EPackage>
