<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="teiidsqlmodel"
    nsURI="http:///org/teiid/datatools/connectivity/teiidsqlmodel.ecore" nsPrefix="TeiidModel">
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="platform:/plugin/org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/ViewTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//TeiidSchema" eOpposite="#//TeiidSchema/Documents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeiidSchema" eSuperTypes="platform:/plugin/org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Documents" upperBound="-1"
        eType="#//Document" eOpposite="#//Document/schema"/>
  </eClassifiers>
</ecore:EPackage>
