<?xml version="1.0" encoding="ASCII"?>
<!--  Copyright (c) 2000-2005 MetaMatrix, Inc.  All rights reserved. -->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="http"
    nsURI="http://schemas.xmlsoap.org/wsdl/http/" nsPrefix="org.xmlsoap.schemas.wsdl.http">
  <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
    <details key="representation" value="schema"/>
    <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AddressType">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="type"/>
      <details key="name" value="addressType"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
    <eReferences name="location" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address" eSuperTypes="#//AddressType">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="element"/>
      <details key="name" value="address"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingType">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="type"/>
      <details key="name" value="bindingType"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
    <eAttributes name="verb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        lowerBound="1">
      <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
        <details key="representation" value="attribute"/>
        <details key="name" value="verb"/>
        <details key="targetNamespace"/>
      </eAnnotations>
    </eAttributes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//BindingType">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="element"/>
      <details key="name" value="binding"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationType">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="type"/>
      <details key="name" value="operationType"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
    <eReferences name="location" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//OperationType">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="element"/>
      <details key="name" value="operation"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UrlEncoded">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="element"/>
      <details key="name" value="urlEncoded"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UrlReplacement">
    <eAnnotations source="http:///org/eclipse/emf/mapping/xsd2ecore/XSD2Ecore">
      <details key="representation" value="element"/>
      <details key="name" value="urlReplacement"/>
      <details key="targetNamespace" value="http://schemas.xmlsoap.org/wsdl/http/"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
