/* Generated By:JJTree: Do not edit this line. Alter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.runtime.client.lang.ast.v8;

import org.teiid.runtime.client.lang.ast.AlterProcedure;
import org.teiid.runtime.client.lang.ast.CreateProcedureCommand;
import org.teiid.runtime.client.lang.parser.LanguageVisitor;
import org.teiid.runtime.client.lang.parser.v8.Teiid8Parser;

/**
 * From Teiid version 8 onwards the AlterProcedure has a CreateProcedureCommand generic
 */
public class Alter8Procedure extends AlterProcedure<CreateProcedureCommand> {

    /**
     * @param p
     * @param id
     */
    public Alter8Procedure(Teiid8Parser p, int id) {
        super(p, id);
    }

    @Override
    public int getType() {
        return TYPE_ALTER_PROC;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(LanguageVisitor visitor) {
        visitor.visit(this);
    }

    @Override
    public Alter8Procedure clone() {
        Alter8Procedure clone = new Alter8Procedure((Teiid8Parser) this.parser, this.id);

        if(getDefinition() != null)
            clone.setDefinition(getDefinition().clone());
        if(getTarget() != null)
            clone.setTarget(getTarget().clone());
        if(getSourceHint() != null)
            clone.setSourceHint(getSourceHint());
        if(getOption() != null)
            clone.setOption(getOption().clone());

        return clone;
    }

}
/* JavaCC - OriginalChecksum=4c2a7e700d4af2b1569d4947a1d82223 (do not edit this line) */
